# Generated by Django 5.2.4 on 2025-07-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_cliente_locacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('parcialmente_pago', '30% Pago'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
    ]
