# Generated by Django 5.2.4 on 2025-07-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_clientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
